$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$failed = 0
$passed = 0
function Assert-True([bool]$Condition, [string]$Message) {
    if ($Condition) { $script:passed++; Write-Host "PASS: $Message"; return }
    $script:failed++; Write-Host "FAIL: $Message" -ForegroundColor Red
}
function Read-Repo([string]$Path) {
    $full = Join-Path $root $Path
    Assert-True (Test-Path -LiteralPath $full -PathType Leaf) "存在 $Path"
    if (Test-Path -LiteralPath $full -PathType Leaf) { return Get-Content -LiteralPath $full -Raw }
    return ''
}
$domain = Read-Repo 'crates/codex-domain/src/switch.rs'
$application = Read-Repo 'crates/codex-application/src/switch.rs'
$migration = Read-Repo 'crates/local-infrastructure/migrations/0003_switch_transaction.sql'
$rootGuardMigration = Read-Repo 'crates/local-infrastructure/migrations/0004_switch_root_guard.sql'
$sensitiveOwnerMigration = Read-Repo 'crates/local-infrastructure/migrations/0010_switch_sensitive_temp_owner.sql'
$migrationEngine = Read-Repo 'crates/local-infrastructure/src/migration.rs'
$repository = Read-Repo 'crates/local-infrastructure/src/repository.rs'
$executor = Read-Repo 'crates/local-infrastructure/src/switch.rs'
$tests = Read-Repo 'crates/local-infrastructure/tests/m23_switch.rs'
$ownerTests = Read-Repo 'crates/local-infrastructure/tests/m23_sensitive_temp_owner.rs'
$windowsPrimitive = Read-Repo 'crates/windows-platform/src/sensitive_temp.rs'
$windowsTests = Read-Repo 'crates/windows-platform/tests/sensitive_temp.rs'
$releaseHistory = Read-Repo 'docs/engineering/m2-sensitive-temp-release-history.md'
$residueGate = Read-Repo 'scripts/m2.3/Test-M23Residue.ps1'
Assert-True ($domain -match 'SwitchTransactionState') '领域层定义持久事务状态'
Assert-True ($domain -match 'RecoveryRequired') '领域层定义 recovery_required'
Assert-True ($application -match 'SwitchTransactionRepository') '应用边界定义事务仓储端口'
Assert-True ($application -match 'SwitchPlan') '应用边界定义带双文件基线的计划'
Assert-True ($application -match 'list_blocking_switch_transactions') '应用端口区分根级阻塞事务'
Assert-True ($application -match 'list_recovery_required_diagnostics') '应用端口提供人工恢复只读诊断查询'
Assert-True ($migration -match 'switch_transactions') 'schema v3 保存非秘密事务摘要'
Assert-True ($migration -match 'snapshot_manifest_sha256') 'schema v3 将快照 manifest 摘要绑定到事务'
Assert-True ($migration -match "targets_replaced','verified','committed'.*completed_roles = 3") 'schema v3 约束完成状态角色位'
Assert-True ($migrationEngine -match 'LATEST_SCHEMA_VERSION: u32 = (?:[4-9]|[1-9][0-9]+)') 'migration engine 保留并演进 schema v4 根级保护'
Assert-True ($rootGuardMigration -match 'CREATE UNIQUE INDEX ux_switch_transactions_active_root') 'schema v4 建立根级单活跃事务唯一索引'
Assert-True ($rootGuardMigration -match "WHERE state NOT IN \('committed','rolled_back'\)") 'schema v4 仅释放 committed/rolled_back 根槽位'
Assert-True ($rootGuardMigration -match 'snapshot binding required') 'schema v4 约束角色位与 snapshot manifest 绑定'
Assert-True ($sensitiveOwnerMigration -match 'switch_sensitive_temp_owners' -and $sensitiveOwnerMigration -match 'prewrite_delete_armed' -and $sensitiveOwnerMigration -match 'cleanup_delete_armed') 'schema v10 持久化敏感临时文件 owner 生命周期'
Assert-True ($sensitiveOwnerMigration -match 'readonly_clear_armed' -and $sensitiveOwnerMigration -match 'switch_sensitive_temp_owner_blocks_terminal') 'schema v10 持久 readonly guard 并阻断未收敛终态'
Assert-True ($repository -match "state NOT IN \('committed','rolled_back'\)") '根级阻塞查询包含 recovery_required'
Assert-True ($repository -match "state NOT IN \('committed','rolled_back','recovery_required'\)") '自动恢复查询排除 recovery_required'
Assert-True ($executor -match 'CrossProcessWriteLock') '基础设施提供跨进程写锁'
Assert-True ($executor -match 'snapshot.manifest') '基础设施持久化版本化联合快照 manifest'
Assert-True ($executor -match 'const SNAPSHOT_VERSION: u32 = 3') 'snapshot manifest v3 绑定源与目标权限证据'
Assert-True ($executor -match 'DpapiCurrentUser' -and $executor -match 'AUTH_SNAPSHOT_MAGIC') '认证快照使用版本化 CurrentUser-DPAPI envelope'
Assert-True ($executor -match 'reconcile_terminal_material' -and $executor -match 'cleanup.intent') '终态材料清理由持久 intent 支持重开幂等收敛'
Assert-True ($executor -match 'SensitiveTempIo' -and $executor -match 'create_sensitive_temp_owner' -and $executor -match 'reconcile_sensitive_temp_owners') '敏感 stage 使用可注入 I/O 与持久 owner/reconcile'
Assert-True ($windowsPrimitive -match 'RootNamespacePin' -and $windowsPrimitive -match 'FileIdentity128' -and $windowsPrimitive -match 'arm_delete_on_close') '敏感 temp 清理绑定持续句柄与 Volume/FileId128'
Assert-True ($windowsPrimitive -match 'FILE_FLAG_DELETE_ON_CLOSE' -and $windowsPrimitive -match 'create_delete_armed_with_post_create' -and $windowsPrimitive -match 'create_link_relative') '敏感 temp 在 CreateFileW 返回时原子 delete-on-close，并在 durable identity 后句柄相对交接'
Assert-True ($windowsPrimitive -match 'NtSetInformationFile' -and $windowsPrimitive -match 'FILE_RENAME_FLAG_REPLACE_IF_EXISTS \| FILE_RENAME_FLAG_POSIX_SEMANTICS') '发布使用固定 root handle 与官方 rename flags，无 path fallback'
Assert-True ($executor -match 'Result<Zeroizing<Vec<u8>>' -and $executor -notmatch 'plaintext\.to_vec\(\)') 'DPAPI 解密回调到恢复验证全程使用 zeroizing 缓冲'
Assert-True ($executor -match 'config.target.length') 'snapshot manifest 记录目标长度与哈希'
Assert-True ($executor -match 'config.target.readonly') 'snapshot manifest 记录目标 readonly'
Assert-True ($executor -match 'sync_all') '暂存和快照执行文件缓冲刷新'
Assert-True ($executor -match 'rename_relative' -and $executor -match 'MaybePublished' -and $executor -match 'RenameFailedUnknown') '目标发布使用句柄相对 rename 与不确定结果状态'
Assert-True ($executor -match 'recover_root') '执行器提供启动恢复入口'
Assert-True ($executor -match 'pair_matches_observation') '进入 replacing 前重新核对源文件'
Assert-True ($executor -match 'pair_matches_target') '替换边界重新核对混合态和目标态'
Assert-True ($executor -match 'finish_failure') '回滚失败对调用方提升为 recovery_required'
Assert-True ($executor -match 'AfterConfigMakeWritable') '权限变更后 rename 前故障边界已固化'
Assert-True ($executor -match 'pair_matches_snapshot_target') '启动恢复比较目标长度哈希与 readonly'
Assert-True ($executor.IndexOf('CrossProcessWriteLock::try_acquire') -lt $executor.IndexOf('list_blocking_switch_transactions')) '取得 OS 锁后才查询根级 blocker'
Assert-True ($executor.IndexOf('list_blocking_switch_transactions') -lt $executor.IndexOf('create_switch_transaction')) '同一锁临界区内先查询 blocker 再创建事务'
Assert-True ($executor -match 'map_transaction_create_error') '唯一约束竞态使用明确执行错误映射'
Assert-True ($executor -match 'record_requires_snapshot') '恢复按记录 manifest 绑定而非仅按状态推断'
Assert-True ($tests -match 'second_process_observes_lock_contended') '真实第二进程竞争回归已固化'
Assert-True ($tests -match 'fault_matrix_never_commits_mixed_files') '故障矩阵禁止混合文件成功'
Assert-True ($tests -match 'interrupted_reopen_recovery_is_idempotent') '重开恢复幂等回归已固化'
Assert-True ($tests -match 'plan_stale') '计划过期和稳定窗口变化回归已固化'
Assert-True ($tests -match 'rollback_holds_cross_process_lock_until_terminal_state') '回滚全程锁竞争回归已固化'
Assert-True ($tests -match 'external_mutation_matrix_is_never_silently_overwritten') '外部修改矩阵回归已固化'
Assert-True ($tests -match 'coherent_snapshot_tamper_is_rejected_before_live_files_change') '一致篡改快照绑定回归已固化'
Assert-True ($tests -match 'recovery_required_blocks_all_new_switches_for_the_same_root') 'recovery_required 根级阻塞矩阵已固化'
Assert-True ($tests -match 'readonly_is_preserved_by_commit_and_rollback') 'readonly commit/rollback 回归已固化'
Assert-True ($tests -match 'recovery_never_proves_source_or_target_with_wrong_readonly_state') 'readonly 启动恢复证明回归已固化'
Assert-True ($tests -match 'dual_connection_old_precheck_race_has_one_database_root_slot') '双连接旧预检查竞态回归已固化'
Assert-True ($tests -match 'contended_execute_creates_no_transaction_or_material') '锁竞争不创建事务或材料回归已固化'
Assert-True ($tests -match 'database_rejects_two_nonterminal_transactions_for_one_root') '数据库根级单活跃槽回归已固化'
Assert-True ($tests -match 'early_rolling_back_crash_recovery_is_hash_only_and_never_writes_live') '早期 rolling_back 崩溃兼容恢复回归已固化'
Assert-True ($tests -match 'interrupted_snapshot_never_persists_authentication_plaintext') '进行中认证快照零明文回归已固化'
Assert-True ($tests -match 'authentication_snapshot_corruption_and_cross_transaction_substitution_fail_closed') '认证快照损坏与跨事务替换 fail closed 回归已固化'
Assert-True ($tests -match 'terminal_cleanup_faults_reopen_and_converge_without_material') '终态清理故障与重开收敛矩阵已固化'
Assert-True ($tests -match 'owned_auth_stage_cleans_real_short_write_and_io_failures') '普通 auth stage 真实 short/write/flush/sync/reread 故障矩阵已固化'
Assert-True ($tests -match 'owned_auth_recovery_stage_cleans_real_short_write_and_io_failures') '恢复 auth stage 真实 I/O 故障矩阵已固化'
Assert-True ($tests -match 'config_target_and_recovery_use_the_same_handle_owner_without_fragment_residue' -and $tests -match 'CONFIG_OWNER') 'config target/recovery 共用 handle owner 并扫描随机 sentinel 分片'
Assert-True ($tests -match 'cleanup_failure_during_recovery_reopens_from_rolling_back') '敏感 temp cleanup failure 重开收敛已固化'
Assert-True ($tests -match 'open_owned_handle_prevents_external_replacement_and_cleans_exact_object') '持续 owner handle 阻止外部替换并只清理同一对象'
Assert-True ($tests -match 'terminate_process_partial_and_post_rename_crashes_reopen_without_sensitive_residue' -and $tests -match 'HARD_CRASH') 'TerminateProcess 部分写入与 rename 后崩溃回归已固化'
Assert-True ($tests -match 'rename_reported_error_after_success_is_resolved_from_same_handle_before_db_publish') 'rename 错误结果只按同句柄 publish proof 收敛'
Assert-True ($ownerTests -match 'v10_owner_lifecycle_guard_and_terminal_blocker_are_cas_durable') 'schema v10 owner/readonly/terminal CAS 动态回归已固化'
Assert-True ($windowsTests -match 'root_pin_denies_namespace_rename_until_drop' -and $windowsTests -match 'root_pin_denies_ancestor_rename') 'root/ancestor namespace pin 竞态回归已固化'
Assert-True ($windowsTests -match 'delete_on_close_clear_close_survival_and_rearm_are_handle_bound' -and $windowsTests -match 'identity_mismatch_and_rename_false') 'delete disposition capability、identity mismatch 与 rename FALSE 回归已固化'
Assert-True ($releaseHistory -match 'schema v10 是第一个受支持' -and $releaseHistory -match '不解析、adopt、迁移或删除 pre-v10/v1') 'pre-v10/v1 未发布裁决与只读 fail-closed 边界已记录'
Assert-True ($residueGate -match 'M23_RESIDUE_SELFTEST' -and $residueGate -match 'sqlite_auxiliary' -and $residueGate -match 'transaction_material') 'residue gate 覆盖注入自测、SQLite 与事务材料'
if ($failed -gt 0) {
    Write-Host "M2.3 contract failed: $failed failed, $passed passed." -ForegroundColor Red
    exit 1
}
Write-Host "M2.3 contract passed: $passed checks." -ForegroundColor Green
