$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$passed = 0
$failed = 0
function Assert-True([bool]$Condition, [string]$Message) {
    if ($Condition) { $script:passed++; Write-Host "PASS: $Message"; return }
    $script:failed++; Write-Host "FAIL: $Message" -ForegroundColor Red
}
function Read-Repo([string]$Path) {
    $full = Join-Path $root $Path
    Assert-True (Test-Path -LiteralPath $full -PathType Leaf) "存在 $Path"
    if (Test-Path -LiteralPath $full -PathType Leaf) { return Get-Content -LiteralPath $full -Raw }
    return ''
}

$credentialPort = Read-Repo 'crates/codex-application/src/credential_store.rs'
$oauthPort = Read-Repo 'crates/codex-application/src/oauth.rs'
$backupPort = Read-Repo 'crates/codex-application/src/backup.rs'
$windowsStore = Read-Repo 'crates/windows-platform/src/credential_store.rs'
$dpapi = Read-Repo 'crates/windows-platform/src/dpapi.rs'
$windowsJob = Read-Repo 'crates/windows-platform/src/job.rs'
$securePath = Read-Repo 'crates/windows-platform/src/secure_path.rs'
$credentialService = Read-Repo 'crates/local-infrastructure/src/credential_service.rs'
$oauth = Read-Repo 'crates/local-infrastructure/src/oauth.rs'
$backup = Read-Repo 'crates/local-infrastructure/src/backup.rs'
$migration = Read-Repo 'crates/local-infrastructure/migrations/0005_credential_backup.sql'
$recoveryMigration = Read-Repo 'crates/local-infrastructure/migrations/0006_backup_recovery.sql'
$guardMigration = Read-Repo 'crates/local-infrastructure/migrations/0007_m24_r3_recovery_guards.sql'
$timestampMigration = Read-Repo 'crates/local-infrastructure/migrations/0008_credential_recovery_timestamps.sql'
$fingerprintMigration = Read-Repo 'crates/local-infrastructure/migrations/0009_credential_recovery_planned_fingerprint.sql'
$sensitiveTempMigration = Read-Repo 'crates/local-infrastructure/migrations/0010_switch_sensitive_temp_owner.sql'
$credentialTests = Read-Repo 'crates/local-infrastructure/tests/m24_credentials.rs'
$oauthBackupTests = Read-Repo 'crates/local-infrastructure/tests/m24_oauth_backup.rs'
$schemaTests = Read-Repo 'crates/local-infrastructure/tests/m24_schema.rs'
$backupRecoveryTests = Read-Repo 'crates/local-infrastructure/tests/m24_backup_recovery.rs'
$oauthJobTests = Read-Repo 'crates/local-infrastructure/tests/m24_oauth_job.rs'
$windowsManifest = Read-Repo 'crates/windows-platform/Cargo.toml'
$workspaceManifest = Read-Repo 'Cargo.toml'
$adr = Read-Repo 'docs/architecture/adr/0001-m2-rust-core-stack.md'
$codexLayer = Read-Repo 'docs/engineering/codex-layer.md'
$domainModel = Read-Repo 'docs/product/domain-model.md'

Assert-True ($credentialPort -match 'trait CredentialStore') '应用层定义同步 CredentialStore 端口'
Assert-True ($credentialPort -match 'SecretConsumer') '秘密读取仅通过短生命周期 consumer'
Assert-True ($credentialPort -match 'CredentialEnvelopeBinding') 'envelope 绑定凭据 id/kind/schema/version'
Assert-True ($credentialPort -match 'CredentialMutationOwner' -and $credentialPort -match 'begin_mutation' -and $credentialPort -match 'end_mutation') '凭据 mutation owner 覆盖完整 service 工作流'
Assert-True ($credentialPort -match 'fn begin_mutation[\s\S]*Err\(CredentialStoreError::RecoveryRequired\)' -and $credentialPort -match 'fn end_mutation[\s\S]*Err\(CredentialStoreError::RecoveryRequired\)') '未实现 mutation owner 的 Store 默认 fail closed'
Assert-True ($oauthPort -match 'trait OAuthProcessRunner') 'OAuth 进程启动与等待可注入'
Assert-True ($backupPort -match 'BackupKind') '应用边界定义 permanent/history 备份种类'
Assert-True ($windowsStore -match 'WindowsDpapiCredentialStore') 'Windows 平台实现 DPAPI CredentialStore'
Assert-True ($dpapi -match 'CryptProtectData') 'CurrentUser 加密调用 CryptProtectData'
Assert-True ($dpapi -match 'CryptUnprotectData') 'CurrentUser 解密调用 CryptUnprotectData'
Assert-True ($dpapi -match 'CRYPTPROTECT_UI_FORBIDDEN') 'DPAPI 禁止交互 UI'
Assert-True ($dpapi -match 'write_bytes') 'DPAPI 原始明文分配在释放前清零'
Assert-True ($windowsManifest -match 'windows-sys\s*=\s*\{\s*version\s*=\s*"=0\.61\.2"') 'windows-sys 精确锁定 0.61.2'
Assert-True ($windowsManifest -match 'Win32_Foundation') 'windows-sys 只启用 DPAPI 所需 Foundation feature'
Assert-True ($windowsManifest -match 'Win32_Security_Cryptography') 'windows-sys 只启用 DPAPI Cryptography feature'
Assert-True ($windowsManifest -match 'zeroize\s*=\s*"=1\.8\.2"') 'zeroize 精确锁定 1.8.2'
Assert-True ($workspaceManifest -match '"crates/windows-platform"') 'Windows 专用代码隔离在独立平台 crate'
Assert-True ($credentialService -match 'create_api_key') 'API Key 原型提供 create'
Assert-True ($credentialService -match 'rotate_credential') '凭据原型提供 rotate'
Assert-True ($credentialService -match 'read_for_switch') '凭据原型提供 read-for-switch'
Assert-True ($credentialService -match 'delete_credential') '凭据原型提供 delete'
Assert-True ($oauth -match 'CodexAdapter') 'OAuth 产物由严格 CodexAdapter 验证'
Assert-True ($oauth -match 'outside') 'OAuth 隔离检测临时目录外写入'
Assert-True ($backup -match 'PERMANENT') '首次永久备份语义已实现'
Assert-True ($backup -match 'HISTORY_LIMIT') '最近历史轮换上限已固化'
Assert-True ($backup -match 'CrossProcessWriteLock') '备份读取与恢复复用根级 OS 锁'
Assert-True ($backup -match 'expires_at <= created_at') '备份恢复计划检查有效期'
Assert-True ($migration -match 'backup_sets') 'schema v5 保存非秘密备份元数据'
Assert-True ($migration -notmatch '(?i)secret_body|api_key|oauth_json|plaintext') 'schema v5 不包含秘密正文列'
Assert-True ($recoveryMigration -match 'backup_recovery_operations') 'schema v6 持久化备份发布/删除恢复意图'
Assert-True ($recoveryMigration -match 'credential_recovery_operations') 'schema v6 持久化凭据脱敏恢复诊断'
Assert-True ($recoveryMigration -match "phase IN \('prepared','published','metadata_pending','delete_pending','recovery_required'\)" -and $credentialPort -match 'planned_material_ref' -and $credentialPort -match 'CredentialRecoveryPhase[\s\S]*Prepared') '凭据 intent 在文件发布前持久化，prepared 阶段不要求材料哈希'
Assert-True ($recoveryMigration -notmatch '(?i)secret_body|oauth_json|plaintext') 'schema v6 恢复日志不包含秘密正文列'
Assert-True ($guardMigration -match "phase IN \('prepared','validated','published','renamed','metadata_deleted','recovery_required'\)") 'schema v7 固化备份 validated 发布门槛'
Assert-True ($guardMigration -match 'CREATE UNIQUE INDEX ux_credential_recovery_active' -and $guardMigration -match 'credential_recovery_operations\(credential_id\)') 'schema v7 每 credential 单一未解决 operation'
Assert-True ($guardMigration -notmatch 'CREATE UNIQUE INDEX ux_credential_recovery_active[\s\S]*WHERE') 'schema v7 如实使用全量 unique index，resolved 行通过删除收敛'
Assert-True ($guardMigration -notmatch '(?i)secret_body|oauth_json|plaintext') 'schema v7 guard migration 不包含秘密正文列'
Assert-True ($timestampMigration -match 'credential_created_at_unix_ms' -and $timestampMigration -match 'credential_updated_at_unix_ms' -and $timestampMigration -match 'credential_updated_at_unix_ms >= credential_created_at_unix_ms') 'schema v8 将凭据时间与 journal 诊断时间分列并约束顺序'
Assert-True ($timestampMigration -match "operation = 'delete'" -and $timestampMigration -match "phase = 'delete_pending'" -and $timestampMigration -match 'ambiguous_count') 'schema v8 对缺失精确 metadata 的旧 DeletePending 时间戳 fail closed'
Assert-True ($fingerprintMigration -match 'planned_credential_fingerprint' -and $fingerprintMigration -match 'legacy_unbound' -and $fingerprintMigration -match 'planned credential fingerprint required') 'schema v9 新 intent 强制绑定 planned credential fingerprint，v8 遗留未绑定行只读兼容'
Assert-True ($fingerprintMigration -match 'planned credential fingerprint is immutable') 'schema v9 planned credential fingerprint 不可变'
Assert-True ($sensitiveTempMigration -match 'switch_sensitive_temp_owners' -and $sensitiveTempMigration -match 'prewrite_delete_armed' -and $sensitiveTempMigration -match 'cleanup_delete_armed') 'schema v10 持久化敏感临时文件 owner 生命周期'
Assert-True ($sensitiveTempMigration -match 'readonly_clear_armed' -and $sensitiveTempMigration -match 'destination_volume_serial' -and $sensitiveTempMigration -match 'destination_file_id') 'schema v10 持久绑定 readonly destination guard 与文件身份'
Assert-True ($sensitiveTempMigration -match 'switch_sensitive_temp_owner_blocks_terminal' -and $sensitiveTempMigration -match 'ON DELETE RESTRICT') 'schema v10 owner 阻断未收敛事务终态与级联删除'
Assert-True ($sensitiveTempMigration -match 'switch_sensitive_temp_anomalies' -and $sensitiveTempMigration -notmatch '(?i)secret_body|oauth_json|plaintext') 'schema v10 持久化脱敏异常且不含秘密正文列'
Assert-True ($credentialTests -match 'dpapi_current_user_round_trip') 'DPAPI CurrentUser round-trip 回归已固化'
Assert-True ($credentialTests -match 'credential_fault_matrix') 'CredentialStore/SQLite 故障矩阵已固化'
Assert-True ($credentialTests -match 'id_kind_schema_generation_binding') 'DPAPI envelope 全绑定负向回归已固化'
Assert-True ($credentialTests -match 'wrong_kind_delete' -and $credentialTests -match 'wrong_schema_rotate' -and $credentialTests -match 'corrupt_previous_rotate' -and $windowsStore -match 'previous\.schema_fingerprint\(\) != next\.schema_fingerprint\(\)') 'rotate/delete 精确验证旧 envelope 与 next schema binding'
Assert-True ($credentialTests -match 'concurrent_rotate_delete') '凭据 rotate/delete 跨实例互斥回归已固化'
Assert-True ($credentialTests -match 'root_junction' -and $credentialTests -match 'internal_junction_target') '凭据路径与递归删除 no-follow 回归已固化'
Assert-True ($credentialTests -match 'format_gate_only=true' -and $credentialTests -match 'entropy_proven=false' -and $credentialTests -match 'deterministic_valid_shape=accepted_by_validator' -and $credentialTests -match 'fingerprint=unkeyed_sha256_compatibility') 'API Key 仅形态门槛且未宣称熵证明'
Assert-True ($credentialTests -match 'credential_quarantine_reopen_reconcile_is_idempotent' -and $credentialTests -match 'rollback_after_physical_delete=idempotent' -and $credentialTests -match 'quarantine_binding=verified' -and $credentialTests -match 'orphan=0') '凭据 quarantine 绑定验证、中断与物理删除后重试可收敛'
Assert-True ($credentialTests -match 'stage_cleanup_reopen=scavenged' -and $windowsStore -match 'cleanup_stages') '凭据 stage cleanup 失败可由重开路径清理'
Assert-True ($credentialTests -match 'credential_service_mutations_have_cross_connection_single_ownership' -and $credentialTests -match 'create_create=single_owner' -and $credentialTests -match 'rotate_rotate=single_owner' -and $credentialTests -match 'shared_intent_cleared_by_loser=false') '凭据 service 双连接 mutation 只有单 owner'
Assert-True ($credentialTests -match 'read_for_switch_holds_owner_across_metadata_and_defers_consumer_until_freshness_proven' -and $credentialTests -match 'rotate_blocked_by_owner=true' -and $credentialTests -match 'stale_consumer=false' -and $credentialTests -match 'metadata_exact_reread=true') 'read-for-switch 在 owner 锁内复读 metadata 后才交付秘密'
Assert-True ($credentialTests -match 'delete_quarantine_service_recovery_adopt_rollback_cleanup_are_bound_and_idempotent' -and $credentialTests -match 'wrong_binding=rejected' -and $credentialTests -match 'wrong_hash=rejected' -and $credentialTests -match 'adopt=restored' -and $credentialTests -match 'cleanup=deleted') 'delete quarantine 的 service adopt/rollback/cleanup 绑定且幂等'
Assert-True ($credentialTests -match 'terminal_recovery_side_effects_retry_after_journal_clear_failure' -and $credentialTests -match 'create_adopt=converged' -and $credentialTests -match 'delete_adopt=converged' -and $credentialTests -match 'delete_rollback=converged' -and $credentialTests -match 'create_rollback=converged' -and $credentialService -match 'same_reference_exact') '终端副作用成功而 journal clear 失败后四条 recovery 路径可重开收敛'
Assert-True ($credentialTests -match 'read_consumer_panic_releases_owner_before_resuming_unwind' -and $credentialTests -match 'owner_released=true' -and $credentialService -match 'catch_unwind' -and $credentialService -match 'resume_unwind') 'consumer panic 先释放凭据 owner 再继续 unwind'
Assert-True ($credentialService -match 'CredentialRecoveryRepository' -and $credentialService -match 'adopt_recovery' -and $credentialService -match 'rollback_recovery') '凭据恢复诊断与幂等人工入口已实现'
Assert-True ($oauthBackupTests -match 'oauth_helper_state_matrix') 'OAuth 合成 helper 全状态矩阵已固化'
Assert-True ($oauthBackupTests -match 'oauth_capture_id_cannot_escape') 'OAuth 捕获路径越界回归已固化'
Assert-True ($oauthBackupTests -match 'permanent_and_twelve_history_backups_rotate_deterministically') '永久备份与 12 次历史轮换回归已固化'
Assert-True ($oauthBackupTests -match 'rotation_failure_preserves_complete_new_set') '历史轮换删除故障回归已固化'
Assert-True ($oauthBackupTests -match 'unfinished_transaction_referenced_history') '未终结事务引用材料保护回归已固化'
Assert-True ($oauthBackupTests -match 'permanent_idempotency_rejects_corrupt') '永久备份幂等完整性回归已固化'
Assert-True ($schemaTests -match 'schema_v10_is_auditable_and_enforces_recovery_ownership_dynamically') 'schema v10 动态审计、凭据时间、planned fingerprint 与 sensitive-temp owner guard 回归已固化'
Assert-True ($credentialTests -match 'delete_recovery_preserves_rotated_credential_timestamps_across_reopen' -and $credentialTests -match 'M24_DELETE_TIMESTAMP_RECOVERY') 'rotate 后 DeletePending 崩溃、重开 adopt/rollback 与 journal-clear 重试精确恢复时间戳'
Assert-True ($credentialTests -match 'reused_create_and_rotate_intents_reject_different_secret_without_losing_recovery' -and $credentialTests -match 'create_prepared=protected' -and $credentialTests -match 'rotate_published=protected' -and $credentialTests -match 'original_retry=converged') 'Create/Rotate 复用 Prepared/Published intent 时不同 secret fail closed 且原 recovery 可收敛'
Assert-True ($credentialTests -match 'rotate_adopt_consumes_bound_reference_and_retries_exactly_after_clear_failure' -and $credentialTests -match 'rotate_adopt_rejects_any_persistable_committed_reference_deviation' -and $credentialTests -match 'planned_time=consumed' -and $credentialTests -match 'clear_failure_retry=exact' -and $credentialService -match 'is_expected_rotate_predecessor' -and $credentialService -match 'same_reference_exact\(&current, &expected\)') 'Rotate adopt 使用 journal 绑定的完整引用，N+1 重试仅在 exact-match 后清 journal'
Assert-True ($backupRecoveryTests -match 'backup_pair_must_remain_stable_until_publish') '联合备份发布前 stable pair 二次观察回归已固化'
Assert-True ($backupRecoveryTests -match 'BetweenSecondObservations' -and $backupRecoveryTests -match 'AfterValidated' -and $backupRecoveryTests -match 'prepared_publish_is_rolled_back_and_orphan_stage_is_scavenged_after_reopen') '备份 Prepared 不发布、Validated 前后稳定观察与 stage scavenging 已固化'
Assert-True ($backupRecoveryTests -match 'published_permanent_is_adopted') '永久备份 metadata 中断后 adopt 回归已固化'
Assert-True ($backupRecoveryTests -match 'history_delete_interruptions_reconcile') '历史轮换三处中断恢复回归已固化'
Assert-True ($backupRecoveryTests -match 'rotation_cleanup_rejects_nested_junction') '备份清理 no-follow junction 回归已固化'
Assert-True ($backup -match 'manifest\.v2' -and $backup -match 'load_legacy_material') '新备份强绑定 manifest v2 且保留 v1 只读兼容'
Assert-True ($backup -match 'secure_read_contained_file' -and $backup -match 'remove_tree_no_follow') '备份敏感读取与静态 reparse 删除检查已固化'
Assert-True ($backup -match 'Zeroizing') '备份 auth 从解密起由 zeroize-on-drop guard 承载'
Assert-True ($windowsJob -match 'JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE' -and $windowsJob -match 'AssignProcessToJobObject') 'OAuth helper 使用 Job Object 约束进程树'
Assert-True ($securePath -match 'FILE_FLAG_OPEN_REPARSE_POINT' -and $securePath -match 'GetFinalPathNameByHandleW') 'Windows 路径使用 handle no-follow 与最终路径 containment'
Assert-True ($oauthJobTests -match 'descendant_tree_is_terminated' -and $oauthJobTests -match 'capture_root_reparse_replacement') 'OAuth 后代进程与 capture root 重解析回归已固化'
Assert-True ($oauthJobTests -match 'wait_error_still_performs_capture_and_outside_audit_before_cleanup' -and $oauthJobTests -match 'capture_audited=true' -and $oauthJobTests -match 'credential_unchanged=true') 'OAuth wait error 仍先完成 capture/outside 审计与清理'
Assert-True ($oauthJobTests -match 'unconfirmed_process_tree_preserves_diagnostic_and_skips_unsafe_cleanup' -and $oauthJobTests -match 'tree_terminated=false' -and $oauth -match 'ProcessTreeUnconfirmed') 'OAuth 无法证明树终结时保留诊断并跳过竞态审计清理'
Assert-True ($oauthJobTests -match 'active_unconfirmed_tree_returns_before_audit_and_preserves_capture' -and $oauthJobTests -match 'background_write=true' -and $oauthJobTests -match 'audit_called=false' -and $oauthJobTests -match 'cleanup_called=false') 'OAuth 活跃且未确认终结时立即返回，不并发审计或清理'
Assert-True ($adr -match 'TOCTOU' -and $codexLayer -match '同 binding 材料' -and $domainModel -match 'journal hash 到 restore 原子绑定' -and $domainModel -match '未加盐 SHA-256') '文档明确 path/material substitution TOCTOU 与指纹剩余风险'
Assert-True ($adr -match '线性化' -and $codexLayer -match '线性化' -and $domainModel -match '线性化') '备份多次观察只作为检测屏障，不宣称非协作写入下的线性化快照'

if ($failed -gt 0) {
    Write-Host "M2.4 contract failed: $failed failed, $passed passed." -ForegroundColor Red
    exit 1
}
Write-Host "M2.4 contract passed: $passed checks." -ForegroundColor Green
